In [3]:
import numpy as np


In [4]:
a=np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
a.shape

(3,)

In [7]:
b=np.array([[1,2,3],[4,5,6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [10]:
b.dtype

dtype('int32')

In [11]:
a=np.arange(60).reshape(3,4,5)

In [12]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

# Array creation:conversion from other python structure

In [13]:
list_array=np.array([[1,2,3],[4,5,6],[8,9,5]])

In [14]:
list_array

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 5]])

In [15]:
list_array.dtype

dtype('int32')

In [16]:
list_array.shape

(3, 3)

In [17]:
list_array.size

9

In [18]:
np.array({1,2,300})

array({1, 2, 300}, dtype=object)

In [19]:
zeros=np.zeros((2,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [22]:
zeros.shape

(2, 5)

In [23]:
rng=np.arange(10)

In [24]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
lspace=np.linspace(1,5,12)

In [26]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [27]:
emp=np.empty((4,6))

In [28]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.33511290e-306, 1.78019082e-306, 8.45559303e-307],
       [8.06613465e-308, 6.89810244e-307, 1.22387550e-307,
        2.22522596e-306, 8.34423917e-308, 9.79107193e-307]])

In [29]:
emp_like=np.empty_like(lspace)

In [30]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [31]:
ide=np.identity(45)

In [32]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
ide.shape

(45, 45)

In [34]:
arr=np.arange(99)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr.shape

(99,)

In [39]:
s1="hello"

if s1[::-1]==s1:
    print("True")
else:
    print("False")

s2="bob"

if s2[::-1]==s2:
    print("True")
else:
    print("False")

False
True


In [40]:
i3=[1,2,3,[4,5,6]]
out=[]
def removenest(i3):
    for i in i3:
        if type(i)==list:
            removenest(i)
        else:
            out.append(i)
removenest(i3)
print(out)


[1, 2, 3, 4, 5, 6]


In [41]:
x=[[1,2,3],[4,5,6],[7,8,0]]


In [45]:
ar=np.array(x)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [47]:
ar.sum(axis=0)

array([12, 15,  9])

In [48]:
ar.sum(axis=1)

array([ 6, 15, 15])

In [49]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 0]])

In [50]:
ar.flat

In [51]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
0


In [52]:
ar.ndim

2

In [53]:
ar.size

9

In [54]:
ar.nbytes

36

In [59]:
one=np.array([1,3,44,5,6])

In [60]:
one.argmax()

2

In [61]:
one.argmin()

0

In [62]:
one.argsort()

array([0, 1, 3, 4, 2], dtype=int64)

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [64]:
ar.argmin()

8

In [65]:
ar.argmax()

7

In [66]:
ar.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [67]:
ar.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [68]:
ar.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]], dtype=int64)

In [69]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [70]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [71]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [0]])

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [74]:
ar2=np.array([[1,2,1],
             [4,0,6],
             [8,1,0]])

In [75]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [76]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  0]])

In [77]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [78]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 0.        ]])

In [79]:
ar.sum()

36

In [80]:
ar.max()

8

In [81]:
ar.min()

0

In [82]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [83]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [85]:
np.count_nonzero(ar)

8

In [86]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [87]:
ar[1,2]=0

In [88]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [89]:
import sys

In [91]:
py_ar=[0,4,55,2]

In [92]:
np_ar=np.array(py_ar)

In [93]:
sys.getsizeof(1)*len(py_ar)

112

In [95]:
np_ar.itemsize*np_ar.size

16