# Numpy-

1:Initializing numpy array with zero
2:Initializing numpy array with one
3:full(),linespace(),random.ramd(),empty() functions
4:ndim,size,shape,dtype
5:reshape(),arange() functions
6:indexing and slicing
7:operation on numpy array
8:Brodcasting
9:other--.tolist()
10:Flattern
11:CONCAT
12:Zeros_like onces_like
13:identity()
14:eye()
15:sqrt()
16:sum()
17:prod()
18:mean()
19:floor()
20:ceil()
21:rint()
22:sum()
23:prod()
24:subtract()
25:mean()
26:var()
27:std()
28:min()
29:max()
30:argmin()
31:argmax()
32:unique()
33:diagonal()

In [5]:
# Stands for Numerical python and is the core of library for numeric
# and scientific computing

In [1]:
import numpy as np
a=np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [7]:
b=np.array((4,5,6))

In [8]:
b

array([4, 5, 6])

In [9]:
type(b)

numpy.ndarray

# Initializing Numpy Array with zero

In [10]:
x=np.zeros((3,4))

In [11]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
x=np.zeros((4,4))

In [13]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
x=np.ones((3,4),dtype=int)

In [15]:
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
x=np.ones((3,4))

In [17]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
x=np.full((3,4),0.11)

In [19]:
x

array([[0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11]])

In [20]:
x=np.arange(10,30,5)


In [21]:
x

array([10, 15, 20, 25])

In [22]:
x=np.linspace(0,5/3,6)

In [23]:
x

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [24]:
x=np.linspace(1,6,6)

In [25]:
x

array([1., 2., 3., 4., 5., 6.])

In [26]:
x=np.random.rand(2,3)

In [27]:
x

array([[0.68373814, 0.56226987, 0.27616635],
       [0.69879091, 0.28288373, 0.63367543]])

In [28]:
x=np.empty((2,3))

In [29]:
x

array([[0.68373814, 0.56226987, 0.27616635],
       [0.69879091, 0.28288373, 0.63367543]])

In [30]:
a.ndim

1

In [31]:
a.size

3

In [32]:
x.size

6

In [33]:
x.shape

(2, 3)

In [34]:
x.dtype

dtype('float64')

In [35]:
a.dtype

dtype('int32')

In [36]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [37]:
b=a.reshape(2,3)

In [38]:
print(b)

[[0 1 2]
 [3 4 5]]


In [39]:
b=a.reshape(1,6)

In [40]:
print(b)

[[0 1 2 3 4 5]]


In [41]:
a=np.array([1,5,3,19,13,7,3])

In [42]:
a[3]

19

In [43]:
a[2:5]

array([ 3, 19, 13])

In [44]:
a[2::2]

array([ 3, 13,  3])

In [45]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

In [46]:
a=np.array([1,2,5,7,8])
a[1:3]=-1

In [47]:
a

array([ 1, -1, -1,  7,  8])

In [48]:
a=[1,2,5,7,8]

In [49]:
a[1:3]=-1

TypeError: can only assign an iterable

In [50]:
a=np.array([1,2,5,7,8])
a_slice=a[1:5]
a_slice[1]=1000

In [51]:
a

array([   1,    2, 1000,    7,    8])

In [52]:
another_slice=a[2:6].copy

In [53]:
a=np.array([1,2,5,7,8])
another_slice=a[2:6].copy
a_slice[1]=1000


In [54]:
a

array([1, 2, 5, 7, 8])

In [59]:
a=np.arange(12).reshape(3,4)
rows_on=np.array([True,False,True])
a[rows_on , :]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [62]:
cols_on=[True,False,True,False]


In [63]:
a[:,cols_on]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [64]:
import numpy as np

In [65]:
a=np.array([10,20,30,40])

In [66]:
b=np.arange(4)

In [67]:
a

array([10, 20, 30, 40])

In [68]:
b

array([0, 1, 2, 3])

# addition

In [69]:
c=a+b

In [70]:
c

array([10, 21, 32, 43])

# substraction

In [71]:
d=a-b

In [72]:
d

array([10, 19, 28, 37])

# multiplication

In [73]:
e=a*b

In [74]:
e

array([  0,  20,  60, 120])

# brodcasting

In [75]:
h=np.arange(5).reshape(1,1,5)

In [76]:
h

array([[[0, 1, 2, 3, 4]]])

In [77]:
h.ndim

3

In [78]:
h+[10,20,30,40,50]

array([[[10, 21, 32, 43, 54]]])

In [ ]:
# 2 rule

In [79]:
np.arange(3)

array([0, 1, 2])

In [80]:
np.arange(3)+5

array([5, 6, 7])

In [84]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [87]:
np.ones((3,3))+np.arange(9).reshape(3,3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [90]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
np.ones((3,3))+np.arange(9).reshape(3,3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [93]:
np.arange(3).reshape(3,1)

array([[0],
       [1],
       [2]])

In [94]:
np.arange(3).reshape(3,1)+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [95]:
k=np.arange(6).reshape(2,3)

In [96]:
k

array([[0, 1, 2],
       [3, 4, 5]])

In [98]:
k+[100,200,300]

array([[100, 201, 302],
       [103, 204, 305]])

# some other

In [101]:
a=np.array([10,20,30,40])

In [102]:
a

array([10, 20, 30, 40])

In [103]:
a.tolist()

[10, 20, 30, 40]

# Flatten

In [104]:
# flattern from higher to lower diamension

In [105]:
a=np.array(range(6),float).reshape((2,3))

In [106]:
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [107]:
a.flatten()

array([0., 1., 2., 3., 4., 5.])

# CONCAT

In [111]:
a=np.array([1,2],float)
b=np.array([3,4,5],float)
c=np.array([6,7,8],float)


In [112]:
np.concatenate((a,b,c))

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [113]:
np.concatenate([a,b,c])

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [114]:
a=np.array([[1,2],[3,4]],float)
b=np.array([[5,6],[7,8]],float)





In [115]:
a

array([[1., 2.],
       [3., 4.]])

In [116]:
b

array([[5., 6.],
       [7., 8.]])

In [117]:
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [118]:
np.concatenate((a,b),axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [119]:
np.concatenate((a,b),axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [123]:
# NEW AXIS

In [130]:
a=np.array((1,2,3))

In [131]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [132]:
a[:,np.newaxis].shape

(3, 1)

In [133]:
a.shape

(3,)

In [134]:
b

array([[5., 6.],
       [7., 8.]])

In [135]:
b.flatten()[:,np.newaxis]

array([[5.],
       [6.],
       [7.],
       [8.]])

# zeros_like and onces_like

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]],float)

In [3]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.identity(4,dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.eye(4,k=1,dtype=float)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [9]:
np.eye(4,k=2,dtype=float)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
a=np.array([1,4,9],float)

In [13]:
np.sqrt(a)

array([1., 2., 3.])

In [15]:
a=np.array([1.1,1.5,1.9],float)

In [16]:
np.floor(a)

array([1., 1., 1.])

In [17]:
np.ceil(a)

array([2., 2., 2.])

In [18]:
np.rint(a)

array([1., 2., 2.])

In [19]:
np.pi

3.141592653589793

In [20]:
np.e

2.718281828459045

In [21]:
a=np.array([[1,2],[3,4],[5,6]],float)

In [23]:
for i in a:
    print(i)

[1. 2.]
[3. 4.]
[5. 6.]


In [26]:
a=np.array([2,4,3],float)

In [27]:
a.sum()

9.0

In [28]:
np.sum(a)

9.0

In [29]:
np.prod(a)

24.0

In [30]:
np.subtract(a,a)

array([0., 0., 0.])

In [31]:
a.mean()

3.0

In [32]:
np.mean(a)

3.0

In [33]:
a.var()

0.6666666666666666

In [34]:
a.std()

0.816496580927726

In [35]:
a.min()

2.0

In [38]:
a.max()

4.0

In [40]:
a.argmin()

0

In [42]:
a.argmax()

1

In [44]:
a=np.array([[0,2],[3,-1],[3,5]],float)

In [45]:
a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [46]:
a.mean()

2.0

In [47]:
a.mean(axis=1)

array([1., 1., 4.])

In [48]:
a.mean(axis=0)

array([2., 2.])

In [50]:
a.max(axis=0)

array([3., 5.])

In [54]:
a=np.array([1,1,4,5,5,5,7],float)

In [55]:
a

array([1., 1., 4., 5., 5., 5., 7.])

In [56]:
np.unique(a)

array([1., 4., 5., 7.])

In [60]:
a=np.array([[1,2],[3,4]],float)

In [61]:
a.diagonal()

array([1., 4.])

In [63]:
a=np.array([1,3,0],float)
b=np.array([0,3,2],float)

In [64]:
a>b

array([ True, False, False])

In [65]:
a==b

array([False,  True, False])

In [66]:
a<=b

array([False,  True,  True])

In [67]:
a>=b

array([ True,  True, False])

In [68]:
a>b

array([ True, False, False])

In [79]:
a=np.array([True,False,False],bool)
b=np.array([True,False,True],bool)
c=np.array([False,True,False],bool)


In [80]:
any(a)

True

In [81]:
all(a)

False

In [82]:
a=np.array([1,3,0],float)

In [83]:
np.logical_and(a>0,a<3)

array([ True, False, False])

In [84]:
np.logical_not(b)

array([False,  True, False])

In [85]:
np.logical_or(b,c)

array([ True,  True,  True])

In [86]:
a=np.array([1,3,0],float)

In [87]:
np.where(a>0,3,2) #

array([3, 3, 2])

In [88]:
a=np.array([[0,1],[3,0]],float)

In [89]:
a

array([[0., 1.],
       [3., 0.]])

In [90]:
a.nonzero()

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [91]:
a=np.array([1,np.NaN,np.Inf],float)

In [92]:
a

array([ 1., nan, inf])

In [93]:
np.isnan(a)

array([False,  True, False])

In [94]:
np.isfinite(a)

array([ True, False, False])

In [95]:
a=np.array([[6,4],[5,9]],float)

In [96]:
a>=6

array([[ True, False],
       [False,  True]])

In [97]:
a[a>=6]

array([6., 9.])

In [98]:
a=np.array([[6,4],[5,9]],float)

In [99]:
sel=(a>=6)

In [100]:
a[sel]

array([6., 9.])

In [101]:
a[np.logical_and(a>5,a<9)]

array([6.])

In [106]:
a=np.array([2,4,6,8],float)
b=np.array([0,0,1,3,2,1],int)

In [107]:
a[b]

array([2., 2., 4., 8., 6., 4.])

In [111]:
a=np.array([[1,4],[9,6]],float)
b=np.array([0,0,1,1,0],int)
c=np.array([0,1,1,1,1],int)

In [112]:
a

array([[1., 4.],
       [9., 6.]])

In [113]:
a[b,c]

array([1., 4., 6., 6., 4.])

In [115]:
a=np.array([2,4,6,8],float)
b=np.array([0,0,1,3,2,1],int)

In [116]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [117]:
a=np.array([[0,1],[2,3]],float)

In [118]:
a

array([[0., 1.],
       [2., 3.]])

In [119]:
b=np.array([0,0,1],int)

In [120]:
b

array([0, 0, 1])

In [121]:
a.take(b,axis=0)

array([[0., 1.],
       [0., 1.],
       [2., 3.]])

In [122]:
a.take(b,axis=1)

array([[0., 0., 1.],
       [2., 2., 3.]])

In [123]:
a=np.array([0,1,2,3,4,5],float)

In [124]:
b=np.array([9,8,7],float)

In [125]:
a.put([0,3],b)

In [126]:
a

array([9., 1., 2., 8., 4., 5.])

In [127]:
a=np.array([0,1,2,3,4,5],float)

In [128]:
a.put([0,3],5)

In [129]:
a

array([5., 1., 2., 5., 4., 5.])